language: cpp

matrix:
  include:
    - os: linux
      env: Linux
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      script:
        - mkdir build
        - cd build
        - export CC=gcc-5 && export CXX=g++-5
        - cmake -DENABLE_CODE_COVERAGE=ON ..
        - make -j
        - test/fs-test -s -r compact
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      env: Android
      dist: trusty
      before_install:
        - curl -L https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
        - unzip -oq android-ndk-r16b-linux-x86_64.zip
        - export NDK_ROOT=$PWD/android-ndk-r16b
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=19 -DCMAKE_ANDROID_NDK=$NDK_ROOT -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=c++_shared ..
        - make -j

    - os: osx
      env: macOS
      osx_image: xcode9
      script:
        - mkdir build
        - cd build
        - cmake -G Xcode ..
        - xcodebuild -target fs-test -project libfs.xcodeproj -configuration Debug
        - test/Debug/fs-test -s -r compact

    - os: osx
      env: iOS
      osx_image: xcode9
      before_install:
        - curl -L https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake -O
        - export IOS_TOOLCHAIN=$PWD/ios.toolchain.cmake
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_TOOLCHAIN_FILE=$IOS_TOOLCHAIN -DENABLE_BITCODE=NO -DIOS_PLATFORM=OS ..
        - make -j