os: Visual Studio 2017

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

shallow_clone: true

clone_folder: c:\projects\libfs

before_build:
  - pwd
  - cmake --version
  - echo %platform% %configuration%
  - if %platform%==x64 (set arch="Win64") else (set arch="Win86")
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 %arch%" ..

build:
  project: C:\projects\libfs\build\libfs.sln

test_script:
  - pwd
  - ls
  - test\%configuration%\fs-test.exe